import type { Metadata } from "next";
import "./globals.css";
import { HeadersFont, BodyFonts } from "../utils/customFonts";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${HeadersFont.variable} ${BodyFonts.className}`}>
        {children}
      </body>
    </html>
  );
}
