import type { Metadata } from "next";
import "./globals.css";
import { HeadersFont, BodyFonts } from "../utils/customFonts";
import Header from "@/components/Header";
import { ClerkProvider } from "@clerk/nextjs";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={`${HeadersFont.variable} ${BodyFonts.className}`}>
          <Header />
          {children}
        </body>
      </html>
    </ClerkProvider>
  );
}
